# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./MasterMealMind

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: EF Tool inst
      run: dotnet tool install --global dotnet-ef --version 7.0.14
    - name: Apply EF Core Migrations
      run: dotnet ef database update --project ./MasterMealMind.API --configuration Debug

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        DB_CONNECTION_STRING: ${{ secrets.CONN_TOKEN }}
      run: dotnet test --verbosity normal
